name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
    paths: 
      - 'hugging_face_space/**'
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout repository
       uses: actions/checkout@v4
     - name: Clone Hugging Face Space
       run: |
         git clone https://IanStedham:$HF_TOKEN@huggingface.co/spaces/IanStedham/fullGitHFConnectTest hf_space
       env:
         HF_TOKEN: ${{ secrets.HF_TOKEN }}
     - name: Copy Selected Files
       run: |
         cd hf_space
         cp ../hugging_face_space/app.py .
         cp ../hugging_face_space/requirements.txt .
         cp ../hugging_face_space/.gitattributes .
         cp ../hugging_face_space/README.md .
         cp ../hugging_face_space/respond_params.txt .
         git add app.py requirements.txt .gitattributes README.md respond_params.txt
         git commit -m "Update selected files"
         git push

